# Generated by Django 2.0.7 on 2018-07-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [

    ]
