# Generated by Django 2.0.7 on 2018-07-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20180722_1612'),
        ('image', '0002_remove_image_headshot_ppoi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
